from __future__ import annotations

import re

RAW_SYMPTOM_CONVERSION = {
    "anxiety and nervousness": "symptom__anxiety",
    "depressive or psychotic symptoms": "symptom__psychological_distress",
    "sharp chest pain": "symptom__chest_pain",
    "abnormal involuntary movements": "symptom__tremor",
    "palpitations": "symptom__heart_palpitations",
    "breathing fast": "symptom__rapid_breathing",
    "throat swelling": "symptom__swollen_throat",
    "diminished hearing": "symptom__hearing_loss",
    "lump in throat": "symptom__swollen_throat",
    "throat feels tight": "symptom__swollen_throat",
    "difficulty in swallowing": "symptom__difficulty_swallowing",
    "skin swelling": "symptom__swelling",
    "retention of urine": "symptom__urinary_retention",
    "suprapubic pain": "symptom__pelvic_pain",
    "emotional symptoms": "symptom__psychological_distress",
    "elbow weakness": "symptom__arm_weakness",
    "back weakness": "symptom__back_weakness",
    "pus in sputum": "symptom__cough_with_phlegm",
    "symptoms of the scrotum and testes": "symptom__testicular_pain",
    "swelling of scrotum": "symptom__testicular_pain",
    "pain in testicles": "symptom__testicular_pain",
    "flatulence": "symptom__gas",
    "pus draining from ear": "symptom__ear_discharge",
    "mass in scrotum": "symptom__testicular_pain",
    "white discharge from eye": "symptom__eye_discharge",
    "abusing alcohol": "symptom__alcohol_intoxication",
    "hostile behavior": "symptom__agitation",
    "drug abuse": "symptom__drug_overdose",
    "sharp abdominal pain": "symptom__abdominal_pain",
    "feeling ill": "symptom__very_unwell",
    "diarrhea": "symptom__diarrhoea",
    "involuntary urination": "symptom__incontinence",
    "pain during intercourse": "symptom__pain_during_sex",
    "lower abdominal pain": "symptom__abdominal_pain",
    "hot flashes": "symptom__sweating",
    "intermenstrual bleeding": "symptom__vaginal_bleeding",
    "hand or finger pain": "symptom__joint_pain",
    "wrist pain": "symptom__joint_pain",
    "hand or finger swelling": "symptom__swollen_joint",
    "arm pain": "symptom__arm_pain",
    "wrist swelling": "symptom__swollen_joint",
    "arm stiffness or tightness": "symptom__stiffness",
    "arm swelling": "symptom__swelling",
    "hand or finger stiffness or tightness": "symptom__joint_stiffness",
    "wrist stiffness or tightness": "symptom__joint_stiffness",
    "abnormal appearing skin": "symptom__rash",
    "skin lesion": "symptom__rash",
    "acne or pimples": "symptom__boil",
    "dry lips": "symptom__dry_mouth",
    "facial pain": "symptom__facial_pain",
    "diminished vision": "symptom__vision_loss",
    "symptoms of eye": "symptom__eye_pain",
    "pain in eye": "symptom__eye_pain",
    "foreign body sensation in eye": "symptom__foreign_body_in_eye",
    "low back pain": "symptom__back_pain",
    "pain during pregnancy": "symptom__pregnancy_pain_or_bleeding",
    "infant spitting up": "symptom__vomiting",
    "regurgitation": "symptom__vomiting",
    "regurgitation.1": "symptom__vomiting",
    "burning abdominal pain": "symptom__abdominal_pain",
    "restlessness": "symptom__agitation",
    "peripheral edema": "symptom__swollen_legs",
    "jaw swelling": "symptom__facial_swelling",
    "mouth dryness": "symptom__dry_mouth",
    "neck swelling": "symptom__swollen_throat",
    "foot or toe pain": "symptom__leg_pain",
    "ankle pain": "symptom__leg_pain",
    "bones are painful": "symptom__bone_pain",
    "knee weakness": "symptom__leg_weakness",
    "elbow pain": "symptom__joint_pain",
    "knee swelling": "symptom__swollen_joint",
    "problems with movement": "symptom__loss_of_coordination",
    "knee stiffness or tightness": "symptom__joint_stiffness",
    "foot or toe swelling": "symptom__ankle_swelling",
    "infant feeding problem": "symptom__poor_feeding",
    "recent weight loss": "symptom__weight_loss",
    "problems with shape or size of breast": "symptom__breast_lump",
    "underweight": "symptom__weight_loss",
    "difficulty eating": "symptom__difficulty_swallowing",
    "vaginal pain": "symptom__pelvic_pain",
    "decreased heart rate": "symptom__low_blood_pressure",
    "increased heart rate": "symptom__fast_heart_rate",
    "ringing in ear": "symptom__ringing_in_ears",
    "plugged feeling in ear": "symptom__ear_blockage",
    "frontal headache": "symptom__headache",
    "fluid in ear": "symptom__ear_blockage",
    "neck stiffness or tightness": "symptom__neck_stiffness",
    "spots or clouds in vision": "symptom__floaters",
    "lacrimation": "symptom__watery_eyes",
    "itchiness of eye": "symptom__itchy_eyes",
    "blindness": "symptom__vision_loss",
    "eye burns or stings": "symptom__eye_pain",
    "itchy eyelid": "symptom__itchy_eyes",
    "feeling cold": "symptom__chills",
    "decreased appetite": "symptom__loss_of_appetite",
    "excessive appetite": "symptom__increased_hunger",
    "excessive anger": "symptom__agitation",
    "focal weakness": "symptom__facial_or_limb_weakness",
    "slurring words": "symptom__slurred_speech",
    "symptoms of the face": "symptom__facial_swelling",
    "disturbance of memory": "symptom__memory_loss",
    "paresthesia": "symptom__tingling",
    "side pain": "symptom__flank_pain",
    "shoulder stiffness or tightness": "symptom__joint_stiffness",
    "shoulder weakness": "symptom__arm_weakness",
    "arm cramps or spasms": "symptom__muscle_cramps",
    "shoulder swelling": "symptom__swollen_joint",
    "tongue lesions": "symptom__mouth_ulcer",
    "leg cramps or spasms": "symptom__leg_cramps",
    "abnormal appearing tongue": "symptom__mouth_ulcer",
    "ache all over": "symptom__body_aches",
    "lower body pain": "symptom__pain",
    "problems during pregnancy": "symptom__pregnancy_pain_or_bleeding",
    "spotting or bleeding during pregnancy": "symptom__pregnancy_bleeding",
    "cramps and spasms": "symptom__muscle_cramps",
    "upper abdominal pain": "symptom__abdominal_pain",
    "stomach bloating": "symptom__bloating",
    "unusual color or odor to urine": "symptom__smelly_urine",
    "swollen abdomen": "symptom__abdominal_swelling",
    "leg stiffness or tightness": "symptom__joint_stiffness",
    "difficulty breathing": "symptom__breathing_difficulty",
    "rib pain": "symptom__pain_when_breathing",
    "muscle stiffness or tightness": "symptom__stiffness",
    "groin pain": "symptom__pelvic_pain",
    "abdominal distention": "symptom__abdominal_swelling",
    "symptoms of the kidneys": "symptom__kidney_pain",
    "melena": "symptom__black_stool",
    "flushing": "symptom__skin_redness",
    "coughing up sputum": "symptom__cough_with_phlegm",
    "seizures": "symptom__seizure",
    "delusions or hallucinations": "symptom__hallucinations",
    "shoulder cramps or spasms": "symptom__muscle_cramps",
    "joint stiffness or tightness": "symptom__joint_stiffness",
    "pain or soreness of breast": "symptom__breast_pain",
    "excessive urination at night": "symptom__frequent_urination",
    "rectal bleeding": "symptom__blood_in_stool",
    "temper problems": "symptom__agitation",
    "coryza": "symptom__runny_nose",
    "wrist weakness": "symptom__hand_weakness",
    "eye strain": "symptom__eye_pain",
    "hemoptysis": "symptom__coughing_blood",
    "lymphedema": "symptom__swollen_lymph_nodes",
    "skin on leg or foot looks infected": "symptom__skin_infection",
    "congestion in chest": "symptom__chest_congestion",
    "muscle swelling": "symptom__swelling",
    "pus in urine": "symptom__cloudy_urine",
    "low back weakness": "symptom__back_weakness",
    "sleepiness": "symptom__drowsy",
    "apnea": "symptom__breathing_difficulty",
    "abnormal breathing sounds": "symptom__wheezing",
    "elbow cramps or spasms": "symptom__muscle_cramps",
    "feeling hot and cold": "symptom__chills",
    "blood clots during menstrual periods": "symptom__heavy_menstrual_bleeding",
    "absence of menstruation": "symptom__missed_period",
    "gum pain": "symptom__gum_swelling",
    "fluid retention": "symptom__swelling",
    "flu-like syndrome": "symptom__flu_like_symptoms",
    "sinus congestion": "symptom__sinus_pressure",
    "painful sinuses": "symptom__sinus_pain",
    "fears and phobias": "symptom__anxiety",
    "uterine contractions": "symptom__in_labour_or_ruptured_membranes",
    "burning chest pain": "symptom__chest_pain",
    "back cramps or spasms": "symptom__muscle_cramps",
    "stiffness all over": "symptom__stiffness",
    "muscle cramps, contractures, or spasms": "symptom__muscle_cramps",
    "low back cramps or spasms": "symptom__muscle_cramps",
    "long menstrual periods": "symptom__heavy_menstrual_bleeding",
    "heavy menstrual flow": "symptom__heavy_menstrual_bleeding",
    "painful menstruation": "symptom__pelvic_pain",
    "mass on eyelid": "symptom__eye_swelling",
    "swollen eye": "symptom__swollen_eyes",
    "eyelid swelling": "symptom__swollen_eyes",
    "itching of skin": "symptom__itching",
    "hurts to breath": "symptom__pain_when_breathing",
    "skin dryness, peeling, scaliness, or roughness": "symptom__skin_peeling",
    "skin on arm or hand looks infected": "symptom__skin_infection",
    "skin irritation": "symptom__itching",
    "itchy scalp": "symptom__itching",
    "hip swelling": "symptom__swelling",
    "incontinence of stool": "symptom__incontinence",
    "foot or toe cramps or spasms": "symptom__muscle_cramps",
    "bumps on penis": "symptom__genital_sores",
    "skin rash": "symptom__rash",
    "low back swelling": "symptom__swelling",
    "drainage in throat": "symptom__post_nasal_drip",
    "dry or flaky scalp": "symptom__skin_peeling",
    "feeling hot": "symptom__fever",
    "foot or toe stiffness or tightness": "symptom__joint_stiffness",
    "pelvic pressure": "symptom__pelvic_pain",
    "elbow swelling": "symptom__swollen_joint",
    "elbow stiffness or tightness": "symptom__joint_stiffness",
    "bleeding from ear": "symptom__ear_discharge",
    "hand or finger weakness": "symptom__hand_weakness",
    "low self-esteem": "symptom__depression",
    "throat irritation": "symptom__sore_throat",
    "swollen or red tonsils": "symptom__swollen_throat",
    "swollen tongue": "symptom__tongue_swelling",
    "lip sore": "symptom__lip_swelling",
    "vulvar sore": "symptom__genital_sores",
    "hip stiffness or tightness": "symptom__joint_stiffness",
    "mouth pain": "symptom__pain",
    "arm weakness": "symptom__arm_weakness",
    "disturbance of smell or taste": "symptom__loss_of_smell",
    "penis pain": "symptom__genital_sores",
    "obsessions and compulsions": "symptom__anxiety",
    "neck cramps or spasms": "symptom__muscle_cramps",
    "thirst": "symptom__excessive_thirst",
    "sleepwalking": "symptom__sleep_problem",
    "knee cramps or spasms": "symptom__muscle_cramps",
    "leg weakness": "symptom__leg_weakness",
    "bleeding in mouth": "symptom__bleeding_gums",
    "tongue bleeding": "symptom__bleeding_gums",
    "penis redness": "symptom__genital_rash",
    "polyuria": "symptom__frequent_urination",
    "cloudy eye": "symptom__vision_loss",
    "hysterical behavior": "symptom__agitation",
    "nightmares": "symptom__sleep_problem",
    "pain in gums": "symptom__gum_swelling",
    "bedwetting": "symptom__bed_wetting",
    "diaper rash": "symptom__rash",
    "lump or mass of breast": "symptom__breast_lump",
    "vaginal bleeding after menopause": "symptom__vaginal_bleeding",
    "infrequent menstruation": "symptom__missed_period",
    "postpartum problems of the breast": "symptom__breast_pain",
    "hesitancy": "symptom__urinary_retention",
    "muscle weakness": "symptom__weakness",
    "throat redness": "symptom__sore_throat",
    "joint swelling": "symptom__swollen_joint",
    "tongue pain": "symptom__pain",
    "foot or toe weakness": "symptom__foot_weakness",
    "hand or finger cramps or spasms": "symptom__muscle_cramps",
    "back stiffness or tightness": "symptom__back_stiffness",
    "skin pain": "symptom__skin_pain",
    "low back stiffness or tightness": "symptom__back_stiffness",
    "low urine output": "symptom__reduced_urine_output",
    "skin on head or neck looks infected": "symptom__skin_infection",
    "stuttering or stammering": "symptom__difficulty_speaking",
    "hip weakness": "symptom__leg_weakness",
    "back swelling": "symptom__swelling",
    "ankle stiffness or tightness": "symptom__joint_stiffness",
    "ankle weakness": "symptom__foot_weakness",
    "neck weakness": "symptom__neck_weakness",
}


def _normalize_v2_symptom(raw: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "_", (raw or "").lower())
    return s.strip("_")


def map_v2_symptom(raw_name: str, schema_columns: set[str]) -> str | None:
    if raw_name in RAW_SYMPTOM_CONVERSION:
        target = RAW_SYMPTOM_CONVERSION[raw_name]
        return target if target in schema_columns else None
    candidate = f"symptom__{_normalize_v2_symptom(raw_name)}"
    return candidate if candidate in schema_columns else None
