KAGGLE_TO_SCHEMA = {
    "itching": "symptom__itching",
    "skin_rash": "symptom__rash",
    "nodal_skin_eruptions": "symptom__rash",
    "continuous_sneezing": "symptom__sneezing",
    "shivering": "symptom__chills",
    "chills": "symptom__chills",
    "joint_pain": "symptom__joint_pain",
    "stomach_pain": "symptom__abdominal_pain",
    "acidity": "symptom__acid_reflux",
    "ulcers_on_tongue": "symptom__mouth_ulcer",
    "muscle_wasting": "symptom__weakness",
    "vomiting": "symptom__vomiting",
    "burning_micturition": "symptom__painful_urination",
    "spotting_urination": "symptom__blood_in_urine",
    "fatigue": "symptom__fatigue",
    "weight_gain": "symptom__weight_gain",
    "anxiety": "symptom__anxiety",
    "weight_loss": "symptom__weight_loss",
    "restlessness": "symptom__agitation",
    "lethargy": "symptom__fatigue",
    "patches_in_throat": "symptom__sore_throat",
    "cough": "symptom__cough",
    "high_fever": "symptom__high_fever",
    "sunken_eyes": "symptom__dehydration",
    "breathlessness": "symptom__shortness_of_breath",
    "dehydration": "symptom__dehydration",
    "indigestion": "symptom__indigestion",
    "headache": "symptom__headache",
    "yellowish_skin": "symptom__yellow_skin",
    "nausea": "symptom__nausea",
    "loss_of_appetite": "symptom__loss_of_appetite",
    "pain_behind_the_eyes": "symptom__eye_pain",
    "back_pain": "symptom__back_pain",
    "constipation": "symptom__constipation",
    "abdominal_pain": "symptom__abdominal_pain",
    "diarrhoea": "symptom__diarrhoea",
    "mild_fever": "symptom__fever",
    "yellowing_of_eyes": "symptom__jaundice",
    "acute_liver_failure": "symptom__very_unwell",
    "fluid_overload": "symptom__abdominal_swelling",
    "swelling_of_stomach": "symptom__abdominal_swelling",
    "swelled_lymph_nodes": "symptom__swollen_lymph_nodes",
    "malaise": "symptom__very_unwell",
    "blurred_and_distorted_vision": "symptom__blurred_vision",
    "phlegm": "symptom__cough_with_phlegm",
    "throat_irritation": "symptom__sore_throat",
    "redness_of_eyes": "symptom__red_eye",
    "sinus_pressure": "symptom__sinus_pressure",
    "runny_nose": "symptom__runny_nose",
    "congestion": "symptom__nasal_congestion",
    "chest_pain": "symptom__chest_pain",
    "weakness_in_limbs": "symptom__facial_or_limb_weakness",
    "fast_heart_rate": "symptom__fast_heart_rate",
    "bloody_stool": "symptom__blood_in_stool",
    "neck_pain": "symptom__neck_pain",
    "dizziness": "symptom__dizziness",
    "cramps": "symptom__muscle_cramps",
    "bruising": "symptom__bruising",
    "swollen_legs": "symptom__swollen_legs",
    "puffy_face_and_eyes": "symptom__facial_swelling",
    "swollen_extremeties": "symptom__swelling",
    "excessive_hunger": "symptom__increased_hunger",
    "slurred_speech": "symptom__slurred_speech",
    "knee_pain": "symptom__knee_pain",
    "hip_joint_pain": "symptom__hip_pain",
    "muscle_weakness": "symptom__weakness",
    "stiff_neck": "symptom__neck_stiffness",
    "swelling_joints": "symptom__swollen_joint",
    "movement_stiffness": "symptom__stiffness",
    "spinning_movements": "symptom__vertigo",
    "loss_of_balance": "symptom__loss_of_balance",
    "unsteadiness": "symptom__loss_of_balance",
    "weakness_of_one_body_side": "symptom__one_sided_weakness",
    "loss_of_smell": "symptom__loss_of_smell",
    "foul_smell_of_urine": "symptom__smelly_urine",
    "foul_smell_ofurine": "symptom__smelly_urine",
    "continuous_feel_of_urine": "symptom__frequent_urination",
    "passage_of_gases": "symptom__gas",
    "internal_itching": "symptom__itching",
    "toxic_look_(typhos)": "symptom__very_unwell",
    "depression": "symptom__depression",
    "irritability": "symptom__agitation",
    "muscle_pain": "symptom__muscle_pain",
    "altered_sensorium": "symptom__altered_consciousness",
    "red_spots_over_body": "symptom__petechiae",
    "belly_pain": "symptom__abdominal_pain",
    "abnormal_menstruation": "symptom__heavy_menstrual_bleeding",
    "watering_from_eyes": "symptom__watery_eyes",
    "increased_appetite": "symptom__increased_hunger",
    "polyuria": "symptom__frequent_urination",
    "mucoid_sputum": "symptom__cough_with_phlegm",
    "rusty_sputum": "symptom__coughing_blood",
    "visual_disturbances": "symptom__visual_disturbance",
    "coma": "symptom__unconscious",
    "stomach_bleeding": "symptom__vomiting_blood",
    "distention_of_abdomen": "symptom__abdominal_swelling",
    "blood_in_sputum": "symptom__coughing_blood",
    "prominent_veins_on_calf": "symptom__calf_pain",
    "palpitations": "symptom__heart_palpitations",
    "painful_walking": "symptom__leg_pain",
    "pus_filled_pimples": "symptom__pus_discharge",
    "skin_peeling": "symptom__skin_peeling",
    "blister": "symptom__blister",
    "yellow_crust_ooze": "symptom__pus_discharge",
}

# Kaggle "symptoms" we deliberately drop because they are not symptoms in the
# clinical-intake sense (history flags, demographics, lifestyle) or because no
# reasonable proxy exists in the existing schema.
DROPPED_SYMPTOMS = {
    "cold_hands_and_feets",
    "mood_swings",
    "irregular_sugar_level",
    "sweating",
    "dark_urine",
    "yellow_urine",
    "pain_during_bowel_movements",
    "pain_in_anal_region",
    "irritation_in_anus",
    "obesity",
    "swollen_blood_vessels",
    "enlarged_thyroid",
    "brittle_nails",
    "extra_marital_contacts",
    "drying_and_tingling_lips",
    "bladder_discomfort",
    "dischromic_patches",
    "dischromic _patches",
    "family_history",
    "lack_of_concentration",
    "receiving_blood_transfusion",
    "receiving_unsterile_injections",
    "history_of_alcohol_consumption",
    "blackheads",
    "scurring",
    "silver_like_dusting",
    "small_dents_in_nails",
    "inflammatory_nails",
    "red_sore_around_nose",
    "prognosis",
}


def normalize_kaggle_symptom(raw: str) -> str:
    s = (raw or "").strip().lower()
    s = s.replace(" ", "_")
    while "__" in s:
        s = s.replace("__", "_")
    return s
