using System.Collections.Generic;

namespace SACA.WindowsApp.Services
{
    public static class AppLanguage
    {
        private static readonly Dictionary<string, string> English = new()
        {
            ["app_name"] = "Smart Adaptive Clinical Assistant",
            ["back"] = "Back",
            ["welcome"] = "Welcome!",
            ["english"] = "English",
            ["walmajarri"] = "Walmajarri",
            ["triage_assessment"] = "Triage Assessment",
            ["welcome_body"] = "This assessment will help you check your symptoms quickly and understand what to do next.",
            ["get_started"] = "Get Started",
            ["continue"] = "Continue",
            ["assess"] = "Assess",
            ["gender_title"] = "Gender",
            ["gender_male"] = "Male",
            ["gender_female"] = "Female",
            ["gender_unknown"] = "Unknown / Prefer not to say",
            ["age_title"] = "Your Age",
            ["age_younger"] = "65 years old or younger",
            ["age_older"] = "Older than 65",
            ["symptoms_title"] = "Select Any Symptoms",
            ["symptom_fever"] = "Fever",
            ["symptom_diarrhea"] = "Diarrhoea",
            ["symptom_cough"] = "Cough",
            ["symptom_vomiting"] = "Vomiting",
            ["symptom_dizziness"] = "Dizziness",
            ["symptom_runny_nose"] = "Runny Nose",
            ["symptom_eye_pain"] = "Eye Pain",
            ["symptom_sore_throat"] = "Sore Throat",
            ["symptom_headache"] = "Headache",
            ["symptom_joint_pain"] = "Joint Pain",
            ["symptom_abdominal_pain"] = "Abdominal Pain",
            ["symptom_body_pain"] = "Body Pain",
            ["recorded_symptoms"] = "Recorded symptoms:",
            ["severity_title"] = "Severity of Symptoms",
            ["severity_mild"] = "Mild",
            ["severity_low"] = "Low",
            ["severity_moderate"] = "Moderate",
            ["severity_high"] = "High",
            ["severity_severe"] = "Severe",
            ["duration_title"] = "How long have you had these symptoms",
            ["duration_just_began"] = "Just began",
            ["duration_couple_days"] = "A couple days",
            ["duration_more_week"] = "More than a week",
            ["unknown"] = "Unknown",
            ["had_before_title"] = "Have you had these symptoms before?",
            ["chronic_title"] = "Do you have any chronic condition?",
            ["condition_hypertension"] = "Hypertension",
            ["condition_diabetes"] = "Type 2 Diabetes",
            ["condition_heart"] = "Heart Disease",
            ["condition_asthma"] = "Asthma-COPD",
            ["condition_depression"] = "Depression Anxiety",
            ["unknown_none"] = "Unknown / None",
            ["contact_title"] = "Have you been in contact with anyone who is sick recently?",
            ["yes"] = "Yes",
            ["no"] = "No",
            ["voice_gender"] = "Voice answer for gender",
            ["voice_age"] = "Voice answer for age",
            ["voice_symptoms"] = "Voice answer for symptoms",
            ["voice_severity"] = "Voice answer for severity",
            ["voice_duration"] = "Voice answer for duration",
            ["voice_before"] = "Voice answer for previous symptoms",
            ["voice_chronic"] = "Voice answer for chronic conditions",
            ["voice_contact"] = "Voice answer for sick contact",
            ["voice_recording"] = "Voice Recording",
            ["hold_record"] = "Hold to record",
            ["no_recording"] = "No recording",
            ["recording"] = "Recording... release to stop",
            ["processing_voice"] = "Processing voice answer...",
            ["accepted"] = "Accepted",
            ["voice_failed"] = "Voice answer failed",
            ["read_aloud"] = "Read aloud",
            ["speak_gender"] = "Please select your gender, or use the voice recording button to answer.",
            ["speak_age"] = "Please select your age group, or use the voice recording button to answer.",
            ["speak_symptoms"] = "Please select any symptoms you have, or use the voice recording button to describe them.",
            ["speak_severity"] = "Please select how severe your symptoms feel, or use the voice recording button to answer.",
            ["speak_duration"] = "Please select how long you have had these symptoms, or use the voice recording button to answer.",
            ["speak_had_before"] = "Please choose whether you have had these symptoms before, or use the voice recording button to answer.",
            ["speak_chronic"] = "Please select any chronic conditions you have, or choose Unknown or None. You can also use the voice recording button.",
            ["speak_contact"] = "Please choose whether you have been in contact with someone sick recently, or use the voice recording button to answer.",
            ["loading"] = "Analysing symptoms...",
            ["result_title"] = "Triage Result",
            ["severity_level"] = "Severity Level",
            ["recommendation"] = "Recommendation",
            ["symptom_summary"] = "Symptom Summary",
            ["start_again"] = "Start Again",
            ["ok"] = "OK"
        };

        private static readonly Dictionary<string, string> Walmajarri = new()
        {
            ["app_name"] = "Smart Adaptive Clinical Assistant",
            ["back"] = "Kujarra",
            ["welcome"] = "Kaya!",
            ["english"] = "Ingkirriji",
            ["walmajarri"] = "Walmajarri",
            ["triage_assessment"] = "Karlarra Nyurra Yirrarni",
            ["welcome_body"] = "Nyurra yirrarni-rna nyuntu-ku yiwarr-ku nyuntu-ju karlarra nyurra-ju. Kujarra-rna nyuntu-ku yiwarr nyuntu-ju karlarra nyurra-ju.",
            ["get_started"] = "Yirrarni-rna",
            ["continue"] = "Yirrarni",
            ["assess"] = "Yirrarni-rna",
            ["gender_title"] = "Nyuntu Yirrarni",
            ["gender_male"] = "Karli",
            ["gender_female"] = "Yapajarra",
            ["gender_unknown"] = "Karra yimi-rna",
            ["age_title"] = "Nyuntu Jukurra",
            ["age_younger"] = "65 ngurra-wana karrinyanu-wana",
            ["age_older"] = "65 ngurra-wana karrinyanu-warlangu",
            ["symptoms_title"] = "Nyuntu Karlarra Yirrarni",
            ["symptom_fever"] = "Karlarra Waru",
            ["symptom_diarrhea"] = "Karlarra Parnta",
            ["symptom_cough"] = "Karlarra Kurrkurr",
            ["symptom_vomiting"] = "Karlarra Puka",
            ["symptom_dizziness"] = "Karlarra Mirrirr",
            ["symptom_runny_nose"] = "Karlarra Munyju",
            ["symptom_eye_pain"] = "Karlarra Miji",
            ["symptom_sore_throat"] = "Karlarra Juwi",
            ["symptom_headache"] = "Karlarra Kuja",
            ["symptom_joint_pain"] = "Karlarra Jirrpi",
            ["symptom_abdominal_pain"] = "Karlarra Jirri",
            ["symptom_body_pain"] = "Karlarra Yijiji",
            ["recorded_symptoms"] = "Karlarra yirrarni-rna:",
            ["severity_title"] = "Karlarra Yirrarni Jukurra",
            ["severity_mild"] = "Kujarra-wana",
            ["severity_low"] = "Karlarra-wana",
            ["severity_moderate"] = "Yirrarni-wana",
            ["severity_high"] = "Jukurra-wana",
            ["severity_severe"] = "Karlarra Jukurra",
            ["duration_title"] = "Karlarra Nyurra Jukurra",
            ["duration_just_began"] = "Ngurra-wana kujarra",
            ["duration_couple_days"] = "Ngurra-wana karlarra",
            ["duration_more_week"] = "Ngurra-wana karlarra",
            ["unknown"] = "Karra yimi",
            ["had_before_title"] = "Nyuntu karlarra kujarra-wana?",
            ["chronic_title"] = "Nyuntu karlarra jukurra-wana?",
            ["condition_hypertension"] = "Hypertension",
            ["condition_diabetes"] = "Type 2 Diabetes",
            ["condition_heart"] = "Heart Disease",
            ["condition_asthma"] = "Asthma-COPD",
            ["condition_depression"] = "Depression Anxiety",
            ["unknown_none"] = "Karra yimi / None",
            ["contact_title"] = "Nyuntu karlarra-wana nyampuju yimi?",
            ["yes"] = "Yuwayi",
            ["no"] = "Karra",
            ["voice_gender"] = "Yimi-rna nyuntu yirrarni-ku",
            ["voice_age"] = "Yimi-rna nyuntu jukurra-ku",
            ["voice_symptoms"] = "Yimi-rna karlarra-ku",
            ["voice_severity"] = "Yimi-rna karlarra jukurra-ku",
            ["voice_duration"] = "Yimi-rna karlarra nyurra-ku",
            ["voice_before"] = "Yimi-rna karlarra kujarra-ku",
            ["voice_chronic"] = "Yimi-rna karlarra jukurra-ku",
            ["voice_contact"] = "Yimi-rna karlarra-wana-ku",
            ["voice_recording"] = "Yimi Yirrarni-rna",
            ["hold_record"] = "Jijirr-ma Yirrarni-ku",
            ["no_recording"] = "Karra yirrarni",
            ["recording"] = "Yirrarni-rna...",
            ["processing_voice"] = "Yimi Yirrarni-rna...",
            ["accepted"] = "Yuwayi",
            ["voice_failed"] = "Karra yimi yirrarni-rna",
            ["read_aloud"] = "Yimi-rna",
            ["speak_gender"] = "Nyuntu yirrarni yirrarni-rna, manu yimi-rna jijirr-ma yirrarni-ku.",
            ["speak_age"] = "Nyuntu jukurra yirrarni-rna, manu yimi-rna jijirr-ma yirrarni-ku.",
            ["speak_symptoms"] = "Nyuntu karlarra yirrarni-rna, manu yimi-rna jijirr-ma karlarra yirrarni-ku.",
            ["speak_severity"] = "Karlarra jukurra yirrarni-rna, manu yimi-rna jijirr-ma yirrarni-ku.",
            ["speak_duration"] = "Karlarra nyurra jukurra yirrarni-rna, manu yimi-rna jijirr-ma yirrarni-ku.",
            ["speak_had_before"] = "Nyuntu karlarra kujarra-wana yirrarni-rna, manu yimi-rna jijirr-ma yirrarni-ku.",
            ["speak_chronic"] = "Nyuntu karlarra jukurra-wana yirrarni-rna, manu karra yimi yirrarni-rna.",
            ["speak_contact"] = "Nyuntu karlarra-wana nyampuju yirrarni-rna, manu yimi-rna jijirr-ma yirrarni-ku.",
            ["loading"] = "Karlarra yirrarni-rna...",
            ["result_title"] = "Karlarra Yirrarni Jukurra",
            ["severity_level"] = "Karlarra Jukurra",
            ["recommendation"] = "Yimi Karlarra",
            ["symptom_summary"] = "Karlarra Yirrarni Jukurra",
            ["start_again"] = "Yirrarni-rna Kujarra",
            ["ok"] = "Yuwayi"
        };

        public static string CurrentLanguage { get; private set; } = "English";

        public static bool IsWalmajarri => CurrentLanguage == "Walmajarri";

        public static void SetLanguage(string language)
        {
            CurrentLanguage = language == "Walmajarri" ? "Walmajarri" : "English";
        }

        public static string T(string key)
        {
            Dictionary<string, string> dictionary = IsWalmajarri ? Walmajarri : English;
            return dictionary.TryGetValue(key, out string? value)
                ? value
                : English.TryGetValue(key, out string? englishValue) ? englishValue : key;
        }
    }
}
