using System.Collections.Generic;

namespace SACA.WindowsApp.Services
{
    public static class AppLanguage
    {
        private static readonly Dictionary<string, string> English = new()
        {
            ["app_name"] = "Smart Adaptive Clinical Assistant",
            ["back"] = "Back",
            ["welcome"] = "Welcome!",
            ["english"] = "English",
            ["walmajarri"] = "Walmajarri",
            ["triage_assessment"] = "Triage Assessment",
            ["welcome_body"] = "This assessment will help you check how severe your symptoms are and help you know what to do next quickly.",
            ["get_started"] = "Get Started",
            ["clinical_assistant"] = "Clinical Assistant",
            ["assessment"] = "Assessment",
            ["language"] = "Language",
            ["continue"] = "Continue",
            ["assess"] = "Assess",
            ["gender_title"] = "Gender",
            ["gender_page_title"] = "What is Your Gender?",
            ["gender_male"] = "Male",
            ["gender_female"] = "Female",
            ["gender_unknown"] = "Prefer not to say",
            ["age_title"] = "What is Your Age?",
            ["age_younger"] = "65 years old or younger",
            ["age_older"] = "Older than 65 years old",
            ["symptoms_title"] = "What are your symptoms?",
            ["show_more"] = "Show More",
            ["or"] = "OR",
            ["describe_symptoms"] = "Describe Symptoms",
            ["type_details"] = "Type the details...",
            ["symptom_fever"] = "Fever",
            ["symptom_diarrhea"] = "Diarrhea",
            ["symptom_cough"] = "Cough",
            ["symptom_vomiting"] = "Vomiting",
            ["symptom_dizziness"] = "Dizziness",
            ["symptom_runny_nose"] = "Runny Nose",
            ["symptom_eye_pain"] = "Eye Pain",
            ["symptom_sore_throat"] = "Sore throat",
            ["symptom_headache"] = "Headache",
            ["symptom_joint_pain"] = "Joint Pain",
            ["symptom_abdominal_pain"] = "Abdominal Pain",
            ["symptom_body_pain"] = "Body Pain",
            ["recorded_symptoms"] = "Recorded symptoms:",
            ["severity_title"] = "Severity of Symptoms",
            ["severity_mild"] = "Mild",
            ["severity_low"] = "Low",
            ["severity_moderate"] = "Moderate",
            ["severity_high"] = "High",
            ["severity_severe"] = "Severe",
            ["duration_title"] = "Duration of Symptoms",
            ["duration_symptoms_title"] = "Duration of Symptoms",
            ["duration_less_day"] = "Less than a day",
            ["duration_more_day"] = "More than a day",
            ["duration_just_began"] = "Just began",
            ["duration_couple_days"] = "A couple days",
            ["duration_more_week"] = "More than a week",
            ["unknown"] = "Unknown",
            ["had_before_title"] = "Have you had these symptoms Before?",
            ["chronic_title"] = "Do you have any chronic conditions?",
            ["condition_hypertension"] = "Hypertension",
            ["condition_diabetes"] = "Type 2 Diabetes",
            ["condition_heart"] = "Heart Disease",
            ["condition_asthma"] = "Asthma COPDS",
            ["condition_depression"] = "Depression Anxiety",
            ["unknown_none"] = "Unknown / None",
            ["contact_title"] = "Have you been in contact with anyone who is sick recently?",
            ["yes"] = "Yes",
            ["no"] = "No",
            ["voice_gender"] = "Voice answer for gender",
            ["voice_age"] = "Voice answer for age",
            ["voice_symptoms"] = "Voice answer for symptoms",
            ["voice_severity"] = "Voice answer for severity",
            ["voice_duration"] = "Voice answer for duration",
            ["voice_before"] = "Voice answer for previous symptoms",
            ["voice_chronic"] = "Voice answer for chronic conditions",
            ["voice_contact"] = "Voice answer for sick contact",
            ["voice_recording"] = "Voice Recording",
            ["hold_record"] = "Hold to Record",
            ["no_recording"] = "No recording",
            ["recording"] = "Recording...",
            ["processing_voice"] = "Transcribing...",
            ["accepted"] = "Answer",
            ["voice_failed"] = "Could not process this recording. Please try again.",
            ["read_aloud"] = "Listen",
            ["mic"] = "Mic",
            ["mic_permission_required"] = "Microphone permission is required for voice recording.",
            ["recording_process_failed"] = "Could not process this recording. Please try again.",
            ["recording_transcribe_failed"] = "Could not transcribe recording. Please try again.",
            ["verify_symptoms_failed"] = "Could not verify symptoms. Please try again.",
            ["check_symptoms_before_continue"] = "Check symptoms before continuing",
            ["symptoms_not_found"] = "We could not find symptoms from your input. Please select symptoms from the icons or add more details.",
            ["got_it"] = "Got it",
            ["select_or_describe_symptom"] = "Select or describe at least one symptom",
            ["speak_gender"] = "Please select your gender, or use the voice recording button to answer.",
            ["speak_age"] = "Please select your age group, or use the voice recording button to answer.",
            ["speak_symptoms"] = "Please select any symptoms you have, or use the voice recording button to describe them.",
            ["speak_severity"] = "Please select how severe your symptoms feel, or use the voice recording button to answer.",
            ["speak_duration"] = "Please select how long you have had these symptoms, or use the voice recording button to answer.",
            ["speak_had_before"] = "Please choose whether you have had these symptoms before, or use the voice recording button to answer.",
            ["speak_chronic"] = "Please select any chronic conditions you have, or choose Unknown or None. You can also use the voice recording button.",
            ["speak_contact"] = "Please choose whether you have been in contact with someone sick recently, or use the voice recording button to answer.",
            ["loading"] = "Analyzing symptoms",
            ["result_title"] = "Triage Result",
            ["severity_level"] = "Severity Level",
            ["non_urgent"] = "Non Urgent",
            ["semi_urgent"] = "Semi-Urgent",
            ["moderate_result"] = "Moderate",
            ["urgent_result"] = "Urgent",
            ["emergency"] = "Emergency",
            ["immediate"] = "Immediate",
            ["recommendation"] = "Recommendation",
            ["symptom_summary"] = "Symptoms Summary",
            ["possible_condition"] = "Possible Condition",
            ["diagnostic_likely_prefix"] = "You are likely to have",
            ["diagnostic_not_returned"] = "A likely diagnostic condition was not returned by the model.",
            ["save_result"] = "Save the Result",
            ["result_saved"] = "Result saved to gallery",
            ["result_save_failed"] = "Could not save result on this device",
            ["further_review_needed"] = "Further Review Needed",
            ["analysis_unavailable"] = "Sorry, our system is unable to analysis these symptoms. Please speak to a professional healthcare worker for further assessment",
            ["answer"] = "Answer",
            ["listen"] = "Listen",
            ["triage_resuscitation"] = "Resuscitation",
            ["triage_emergent"] = "Emergent",
            ["triage_urgent"] = "Urgent",
            ["triage_less_urgent"] = "Less Urgent",
            ["triage_non_urgent"] = "Non-urgent",
            ["start_again"] = "Start Again",
            ["ok"] = "OK"
        };

        private static readonly Dictionary<string, string> Walmajarri = new()
        {
            ["app_name"] = "Smart Adaptive Clinical Assistant",
            ["back"] = "Kujarra",
            ["welcome"] = "Kaya!",
            ["english"] = "Ingkirriji",
            ["walmajarri"] = "Walmajarri",
            ["triage_assessment"] = "Karlarra Nyurra Yirrarni",
            ["welcome_body"] = "Nyurra yirrarni-rna nyuntu-ku yiwarr-ku nyuntu-ju karlarra nyurra-ju. Kujarra-rna nyuntu-ku yiwarr nyuntu-ju karlarra nyurra-ju.",
            ["get_started"] = "Yirrarni-rna",
            ["clinical_assistant"] = "Karlarra Nyurra Yirrarni",
            ["assessment"] = "Yirrarni",
            ["language"] = "Yimi",
            ["continue"] = "Yirrarni",
            ["assess"] = "Yirrarni-rna",
            ["gender_title"] = "Nyuntu Yirrarni",
            ["gender_page_title"] = "Ngana man Nyuntu Yirrarni?",
            ["gender_male"] = "Karli",
            ["gender_female"] = "Yapajarra",
            ["gender_unknown"] = "Karra yimi-rna",
            ["age_title"] = "Ngana man Nyuntu Jukurra?",
            ["age_younger"] = "65 ngurra-wana karrinyanu-wana",
            ["age_older"] = "65 ngurra-wana karrinyanu-warlangu",
            ["symptoms_title"] = "Ngana man Nyuntu Karlarra Yirrarni?",
            ["show_more"] = "Yirrarni Karlarra",
            ["or"] = "KUJARRA",
            ["describe_symptoms"] = "Karlarra Yirrarni-rna",
            ["type_details"] = "Yimi-rna...",
            ["symptom_fever"] = "Karlarra Waru",
            ["symptom_diarrhea"] = "Karlarra Parnta",
            ["symptom_cough"] = "Karlarra Kurrkurr",
            ["symptom_vomiting"] = "Karlarra Puka",
            ["symptom_dizziness"] = "Karlarra Mirrirr",
            ["symptom_runny_nose"] = "Karlarra Munyju",
            ["symptom_eye_pain"] = "Karlarra Miji",
            ["symptom_sore_throat"] = "Karlarra Juwi",
            ["symptom_headache"] = "Karlarra Kuja",
            ["symptom_joint_pain"] = "Karlarra Jirrpi",
            ["symptom_abdominal_pain"] = "Karlarra Jirri",
            ["symptom_body_pain"] = "Karlarra Yijiji",
            ["recorded_symptoms"] = "Karlarra yirrarni-rna:",
            ["severity_title"] = "Karlarra Yirrarni Jukurra",
            ["severity_mild"] = "Kujarra-wana",
            ["severity_low"] = "Karlarra-wana",
            ["severity_moderate"] = "Yirrarni-wana",
            ["severity_high"] = "Jukurra-wana",
            ["severity_severe"] = "Karlarra Jukurra",
            ["duration_title"] = "Karlarra Nyurra Jukurra",
            ["duration_symptoms_title"] = "Karlarra Nyurra Jukurra",
            ["duration_less_day"] = "Ngurra-wana kujarra",
            ["duration_more_day"] = "Ngurra-wana karlarra",
            ["duration_just_began"] = "Ngurra-wana kujarra",
            ["duration_couple_days"] = "Ngurra-wana karlarra",
            ["duration_more_week"] = "Ngurra-wana karlarra",
            ["unknown"] = "Kulini-wangu",
            ["had_before_title"] = "Nyuntu jangkangu ngarnin ngaa?",
            ["chronic_title"] = "Nyuntu jangkangu kuja-kuja nganayi?",
            ["condition_hypertension"] = "Nungu Tapuk",
            ["condition_diabetes"] = "Linngurru Nungu",
            ["condition_heart"] = "Wataku jangkangu",
            ["condition_asthma"] = "Purru jangkangu",
            ["condition_depression"] = "Kulil-kulil palya-wangu",
            ["unknown_none"] = "Karra yimi / None",
            ["contact_title"] = "Nyuntu marlamarlu jangkangu-warnu ngayu ngurra yurrku?",
            ["yes"] = "Yuwa",
            ["no"] = "Wiya",
            ["voice_gender"] = "Yimi-rna nyuntu yirrarni-ku",
            ["voice_age"] = "Yimi-rna nyuntu jukurra-ku",
            ["voice_symptoms"] = "Yimi-rna karlarra-ku",
            ["voice_severity"] = "Yimi-rna karlarra jukurra-ku",
            ["voice_duration"] = "Yimi-rna karlarra nyurra-ku",
            ["voice_before"] = "Yimi-rna karlarra kujarra-ku",
            ["voice_chronic"] = "Yimi-rna karlarra jukurra-ku",
            ["voice_contact"] = "Yimi-rna karlarra-wana-ku",
            ["voice_recording"] = "Yimi Yirrarni-rna",
            ["hold_record"] = "Jijirr-ma Yirrarni-ku",
            ["no_recording"] = "Karra yirrarni",
            ["recording"] = "Yirrarni-rna...",
            ["processing_voice"] = "Yimi Yirrarni-rna...",
            ["accepted"] = "Pinakarrinyu",
            ["voice_failed"] = "Karra yirrarni-rna karlarra. Yirrarni-rna kujarra.",
            ["read_aloud"] = "Jangulymanu",
            ["mic"] = "Yimi-rna",
            ["mic_permission_required"] = "Yimi-rna karlarra-ku yirrarni-rna nyuntu-ju.",
            ["recording_process_failed"] = "Karra yirrarni-rna karlarra. Yirrarni-rna kujarra.",
            ["recording_transcribe_failed"] = "Karra yimi yirrarni-rna karlarra. Yirrarni-rna kujarra.",
            ["verify_symptoms_failed"] = "Karra karlarra yirrarni-rna. Yirrarni-rna kujarra.",
            ["check_symptoms_before_continue"] = "Karlarra yirrarni-rna kujarra-ku",
            ["symptoms_not_found"] = "Karra karlarra yirrarni-rna nyuntu-ju. Yirrarni-rna karlarra-wana kujarra yimi-rna.",
            ["got_it"] = "Yuwayi",
            ["select_or_describe_symptom"] = "Yirrarni-rna karlarra kujarra-wana yimi-rna",
            ["speak_gender"] = "Nyuntu yirrarni yirrarni-rna, manu yimi-rna jijirr-ma yirrarni-ku.",
            ["speak_age"] = "Nyuntu jukurra yirrarni-rna, manu yimi-rna jijirr-ma yirrarni-ku.",
            ["speak_symptoms"] = "Nyuntu karlarra yirrarni-rna, manu yimi-rna jijirr-ma karlarra yirrarni-ku.",
            ["speak_severity"] = "Karlarra jukurra yirrarni-rna, manu yimi-rna jijirr-ma yirrarni-ku.",
            ["speak_duration"] = "Karlarra nyurra jukurra yirrarni-rna, manu yimi-rna jijirr-ma yirrarni-ku.",
            ["speak_had_before"] = "Nyuntu karlarra kujarra-wana yirrarni-rna, manu yimi-rna jijirr-ma yirrarni-ku.",
            ["speak_chronic"] = "Nyuntu karlarra jukurra-wana yirrarni-rna, manu karra yimi yirrarni-rna.",
            ["speak_contact"] = "Nyuntu karlarra-wana nyampuju yirrarni-rna, manu yimi-rna jijirr-ma yirrarni-ku.",
            ["loading"] = "Karlarra yirrarni-rna...",
            ["result_title"] = "Karlarra Yirrarni Jukurra",
            ["severity_level"] = "Karlarra Jukurra",
            ["non_urgent"] = "Karra Yirrarni",
            ["semi_urgent"] = "Kujarra Yirrarni",
            ["moderate_result"] = "Yirrarni-wana",
            ["urgent_result"] = "Karlarra Yirrarni",
            ["emergency"] = "Jukurra Karlarra",
            ["immediate"] = "Karlarra Nyurra",
            ["recommendation"] = "Yimi Karlarra",
            ["symptom_summary"] = "Karlarra Yirrarni Jukurra",
            ["possible_condition"] = "Karlarra Yirrarni Kujarra",
            ["diagnostic_likely_prefix"] = "Nyuntu-ju karlarra kuja-kuja",
            ["diagnostic_not_returned"] = "Karra karlarra yirrarni-rna nyuntu-ju.",
            ["save_result"] = "Yirrarni-rna Karlarra",
            ["result_saved"] = "Karlarra yirrarni-rna nyuntu-ju",
            ["result_save_failed"] = "Karra karlarra yirrarni-rna nyuntu-ju",
            ["further_review_needed"] = "Karlarra Yirrarni Kujarra",
            ["analysis_unavailable"] = "Karra karlarra yirrarni-rna nyuntu-ju. Yirrarni-rna karlarra-ku yimi karlarra.",
            ["answer"] = "Pinakarrinyu",
            ["listen"] = "Jangulymanu",
            ["triage_resuscitation"] = "Karlarra Wana",
            ["triage_emergent"] = "Karlarra Jukurra",
            ["triage_urgent"] = "Yirrarni Wana",
            ["triage_less_urgent"] = "Yirrarni Kujarra",
            ["triage_non_urgent"] = "Kujarra",
            ["start_again"] = "Yirrarni-rna Kujarra",
            ["ok"] = "Yuwayi"
        };

        public static string CurrentLanguage { get; private set; } = "English";

        public static bool IsWalmajarri => CurrentLanguage == "Walmajarri";

        public static void SetLanguage(string language)
        {
            CurrentLanguage = language == "Walmajarri" ? "Walmajarri" : "English";
        }

        public static string T(string key)
        {
            Dictionary<string, string> dictionary = IsWalmajarri ? Walmajarri : English;
            return dictionary.TryGetValue(key, out string? value)
                ? value
                : English.TryGetValue(key, out string? englishValue) ? englishValue : key;
        }
    }
}
